CREATE TABLE IF NOT EXISTS teams (
	id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
        teamName VARCHAR(150) DEFAULT NULL,
        division VARCHAR(150) DEFAULT NULL
        
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;
